#!/bin/bash

clear

mvfiles(){
    for file in $1; do
        # filetype=$(cut -d. -f2 <<< "$1")
        # I do not beleive that herestrings '<<<' create subshells
        # cp $file /home/nyquist/Development/$filetype/$name
        filetype=${1##*.};
        mkdir /home/nyquist/Development/$filetype/$name
        sudo cp -R * /home/nyquist/Development/$filetype/$name
    done
}

tstdir=/home/nyquist/Development/tst

pattern=\
"[cpp|c|js|py|pl|sh]"

if [[ $PWD =~ ${tstdir}/${pattern} ]]; then
echo -n "name: " 
read name

type=(*.*)
    for file in ${type[@]}; do
        case $file in
            *.cpp) mvfiles *.cpp;;
            *.c)   mvfiles *.c;;
            *.js)  mvfiles *.js;;
            *.py)  mvfiles *.py;;
            *.pl)  mvfiles *.pl;;
            *.sh)  mvfiles *.sh;;
        esac
    done
else
    echo "not a tst directory"
fi
