#!/bin/sh
if [ "$1" == "on" ]; then
    xrandr --output eDP-1 --off
    xrandr --output HDMI-1 --mode 2560x1080
    feh --bg-fill /home/nyquist/Pictures/wallpapers/bf6f697e0eeb6596a1415e31f3e4c1fb.jpg

elif [ "$1" == "off" ]; then
    xrandr --output HDMI-1 --off
    xrandr --output eDP-1 --mode 1920x1080
    feh --bg-fill /home/nyquist/Pictures/wallpapers/bf6f697e0eeb6596a1415e31f3e4c1fb.jpg
fi


